=begin
Lista de Usuarios

Essa API provê o acesso aos usuarios.

OpenAPI spec version: 0.0.1
Contact: claudio@claudio.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_swagger_route 'GET', '/v2/users', controller_name: 'users', action_name: 'index'
  add_swagger_route 'DELETE', '/v2/users/{id}', controller_name: 'users', action_name: 'destroy'
  add_swagger_route 'GET', '/v2/users/{id}', controller_name: 'users', action_name: 'show'
  add_swagger_route 'PATCH', '/v2/users', controller_name: 'users', action_name: 'users_patch'
  add_swagger_route 'POST', '/v2/users', controller_name: 'users', action_name: 'create'
  add_swagger_route 'PUT', '/v2/users', controller_name: 'users', action_name: 'users_put'
end
