=begin
Lista de Usuarios

Essa API provê o acesso aos usuarios.

OpenAPI spec version: 0.0.1
Contact: claudio@claudio.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class UsersController < ApplicationController

  def index
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def destroy
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def show
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def users_patch
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def users_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
