=begin
Lista de Usuarios

Essa API provê o acesso aos usuarios.

OpenAPI spec version: 0.0.1
Contact: claudio@claudio.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class User < ApplicationRecord
  validates_presence_of :email
  validates_presence_of :name

end
